version: "3.9"
services:
  db:
    image: postgres:15
    container_name: wakfu_postgres
    restart: always
    environment:
      POSTGRES_USER: wakfu_user
      POSTGRES_PASSWORD: wakfu
      POSTGRES_DB: wakfu_db
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: wakfu_backend
    restart: on-failure
    env_file: .env
    ports:
      - "4001:4001"
    depends_on:
      - db

volumes:
  pgdata:
